name: Infrastructure checks

on:
  pull_request:
  push:
    branches: [main]

permissions:
  contents: read

jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.16.0"
      - uses: terraform-linters/setup-tflint@v4
        with:
          tflint_version: latest
      - name: Install ShellCheck
        run: sudo apt-get update && sudo apt-get install --yes shellcheck
      - name: Validate
        run: ./scripts/validate.sh
      - name: Checkov
        uses: bridgecrewio/checkov-action@v12
        with:
          directory: .
          framework: terraform
          quiet: true
          soft_fail: false
